### ISSUE TITLE
Intent on servicemonitor

### ISSUE THREAD

**Issue by dirien** [nicolastakashi/cole#1]
**Describe the bug**
Wrong intend on ServiceMonitor

```yaml
# Source: cole/templates/servicemonitor.yaml
kind: ServiceMonitor
...
  selector:
    matchLabels:
    app.kubernetes.io/name: cole
    app.kubernetes.io/instance: cole
```

the fields 
```
app.kubernetes.io/name: cole
app.kubernetes.io/instance: cole
``
should be a child of `matchLabels`


**To Reproduce**
Steps to reproduce the behavior:
`helm template  cole cole/cole --set flags.grafana.namespace=monitoring --set serviceMonitor.enabled=true`
